# 生日與星座
### 輸入生日判斷所輸入生日的星座為何
需要利用每個星座對應的的生日範圍進行判斷

In [2]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact

In [3]:
a=np.random.randint(0,10,size=[3,3])
print(a)
np.linalg.matrix_rank(a)

[[6 1 9]
 [1 1 8]
 [8 8 6]]


3

In [7]:
np.linalg.matrix_rank(a)

3

In [10]:
birthday=int(input(">>"))

>>0214


In [48]:
birthday=1
while not (birthday>=101) or not (birthday<=1231) :
    birthday=int(input("生日>>"))
    if (birthday>=120) & (birthday<=218):
        print("水瓶座")
    elif (birthday>=219) & (birthday<=320):
        print("雙魚座")
    elif (birthday>=321) & (birthday<=419):
        print("牡羊座")
    elif (birthday>=420) & (birthday<=520):
        print("金牛座")
    elif (birthday>=521) & (birthday<=621):
        print("雙子座")
    elif (birthday>=622) & (birthday<=722):
        print("巨蟹座")
    elif (birthday>=723) & (birthday<=822):
        print("獅子座")
    elif (birthday>=823) & (birthday<=922):
        print("處女座")
    elif (birthday>=923) & (birthday<=1023):
        print("天秤座")
    elif (birthday>=1024) & (birthday<=1122):
        print("天蠍座")
    elif (birthday>=1123) & (birthday<=1221):
        print("射手座")
    elif (birthday>=1222) & (birthday<=1231):
        print("摩羯座")
    elif (birthday>=101) & (birthday<=119):
        print("摩羯座")
    else:
        print("別鬧勒")
    

生日>>1
別鬧勒
生日>>101
摩羯座
