# 連連看
## 利用矩陣取出相應範圍內的數字作為題目，再取數字做每一次的答案


In [83]:
import numpy as np
from ipywidgets import interact_manual

輸入有幾位玩家就生成幾組題目

In [97]:
players=int(input("玩家數>>"))
matrix=int(input("想玩幾宮格>>"))
num=int(input("最大的數字為>>"))
col_row=int(matrix**(1/2))

ans=np.random.choice(np.arange(1,num+1),size=num,replace=False)


for i in range(players):
    print(np.random.choice(np.arange(1,num+1),size=matrix,replace=False).reshape(col_row,col_row))
    print("")

for i in range(num):
    print(ans[i])

玩家數>>3
想玩幾宮格>>16
最大的數字為>>100
[[76  9 92 17]
 [33 71  2 18]
 [56 16 68  4]
 [25 10 45 19]]

[[72 81 12 75]
 [44 42 38 84]
 [ 6 30 65 71]
 [93 80  3 67]]

[[96 43 59 92]
 [ 4 56 83  5]
 [95 52 49 42]
 [ 1 84 72 39]]

11
65
35
31
55
73
67
18
69
47
6
36
19
89
45
29
71
27
75
2
66
25
83
52
20
44
3
60
81
74
82
85
68
50
72
8
99
76
40
80
28
100
15
37
22
70
90
87
79
53
38
57
61
77
63
12
17
30
97
58
41
14
64
10
26
23
93
21
43
13
88
96
56
1
33
42
24
39
86
51
34
16
62
95
7
4
54
98
59
49
92
46
5
91
9
94
48
78
84
32
